# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp sourceCpp
#'@useDynLib SSOSVM
NULL

#'@export
SquareHingeC <- function(YMAT, DIM = 2L, EPSILON = 0.00001, returnAll = FALSE) {
    .Call('_SSOSVM_SquareHingeC', PACKAGE = 'SSOSVM', YMAT, DIM, EPSILON, returnAll)
}

#'@export
HingeC <- function(YMAT, DIM = 2L, EPSILON = 0.00001, returnAll = FALSE) {
    .Call('_SSOSVM_HingeC', PACKAGE = 'SSOSVM', YMAT, DIM, EPSILON, returnAll)
}

#'@export
LogisticC <- function(YMAT, DIM = 2L, EPSILON = 0.00001, returnAll = FALSE) {
    .Call('_SSOSVM_LogisticC', PACKAGE = 'SSOSVM', YMAT, DIM, EPSILON, returnAll)
}

